call scrapy crawl chictopia2 -a user="sustainablesiren" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\sustainablesiren" -o data/sustainablesiren.json -t json
call scrapy crawl chictopia2 -a user="nanysklozet" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\nanysklozet" -o data/onanysklozet.json -t json
call scrapy crawl chictopia2 -a user="PamHetlinger" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\PamHetlinger" -o data/PamHetlinger.json -t json
call scrapy crawl chictopia2 -a user="Aphrodite" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\Aphrodite" -o data/Aphrodite.json -t json
call scrapy crawl chictopia2 -a user="gvozd" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\gvozd" -o data/gvozd.json -t json
call scrapy crawl chictopia2 -a user="themoptop" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\themoptop" -o data/themoptop.json -t json
call scrapy crawl chictopia2 -a user="LarisaCostea" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\LarisaCostea" -o data/LarisaCostea.json -t json
call scrapy crawl chictopia2 -a user="Myblondegal" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\Myblondegal" -o data/Myblondegal.json -t json
call scrapy crawl chictopia2 -a user="fitfabfun" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\fitfabfun" -o data/fitfabfun.json -t json
call scrapy crawl chictopia2 -a user="violetheart" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\violetheart" -o data/violetheart.json -t json
call scrapy crawl chictopia2 -a user="selectivepotential" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\selectivepotential" -o data/selectivepotential.json -t json
call scrapy crawl chictopia2 -a user="StardustBohemian" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\StardustBohemian" -o data/StardustBohemian.json -t json
call scrapy crawl chictopia2 -a user="districtofchic" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\districtofchic" -o data/districtofchic.json -t json
call scrapy crawl chictopia2 -a user="HAUTE_INSTINCT" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\HAUTE_INSTINCT" -o data/HAUTE_INSTINCT.json -t json
call scrapy crawl chictopia2 -a user="braNYaudreY" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\braNYaudreY" -o data/braNYaudreY.json -t json
call scrapy crawl chictopia2 -a user="itsnotthatdeep" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\itsnotthatdeep" -o data/itsnotthatdeep.json -t json
call scrapy crawl chictopia2 -a user="inspirafashion" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\inspirafashion" -o data/inspirafashion.json -t json
call scrapy crawl chictopia2 -a user="RuxandraIoana" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\RuxandraIoana" -o data/RuxandraIoana.json -t json
call scrapy crawl chictopia2 -a user="deathbyplatforms" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\deathbyplatforms" -o data/deathbyplatforms.json -t json
call scrapy crawl chictopia2 -a user="queenhorsfall" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\queenhorsfall" -o data/queenhorsfall.json -t json
call scrapy crawl chictopia2 -a user="Fancytreehouse" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\Fancytreehouse" -o data/Fancytreehouse.json -t json
call scrapy crawl chictopia2 -a user="reyalfashion" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\reyalfashion" -o data/reyalfashion.json -t json
call scrapy crawl chictopia2 -a user="RaniaKelesidou" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\RaniaKelesidou" -o data/RaniaKelesidou.json -t json
call scrapy crawl chictopia2 -a user="Laura86" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\Laura86" -o data/Laura86.json -t json
call scrapy crawl chictopia2 -a user="aminta" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\aminta" -o data/aminta.json -t json
call scrapy crawl chictopia2 -a user="HenEvia" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\HenEvia" -o data/HenEvia.json -t json
call scrapy crawl chictopia2 -a user="DevoreLeBeauMonstre" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\DevoreLeBeauMonstre" -o data/DevoreLeBeauMonstre.json -t json
call scrapy crawl chictopia2 -a user="Kryz" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\Kryz" -o data/Kryz.json -t json
call scrapy crawl chictopia2 -a user="FashionZen" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\FashionZen" -o data/FashionZen.json -t json
call scrapy crawl chictopia2 -a user="paxie_aiza" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\paxie_aiza" -o data/paxie_aiza.json -t json
call scrapy crawl chictopia2 -a user="lanton" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\lanton" -o data/lanton.json -t json
call scrapy crawl chictopia2 -a user="michelletakeaim" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\michelletakeaim" -o data/michelletakeaim.json -t json
call scrapy crawl chictopia2 -a user="fashioncoolture" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\fashioncoolture" -o data/fashioncoolture.json -t json
call scrapy crawl chictopia2 -a user="tab" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\tab" -o data/tab.json -t json
call scrapy crawl chictopia2 -a user="lissakahayon" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\lissakahayon" -o data/lissakahayon.json -t json
call scrapy crawl chictopia2 -a user="candydoll" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\candydoll" -o data/candydoll.json -t json
call scrapy crawl chictopia2 -a user="TheBlackFeather" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\TheBlackFeather" -o data/TheBlackFeather.json -t json
call scrapy crawl chictopia2 -a user="reneesturme" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\reneesturme" -o data/reneesturme.json -t json
call scrapy crawl chictopia2 -a user="mochaccinoland" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\mochaccinoland" -o data/mochaccinoland.json -t json
call scrapy crawl chictopia2 -a user="flattery" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\flattery" -o data/flattery.json -t json
call scrapy crawl chictopia2 -a user="slumberdoll" -s IMAGES_STORE="C:\Users\lbpeng\Desktop\chictopia2\images\slumberdoll" -o data/slumberdoll.json -t json
